server:
  port: 8081
  servlet:
    jsp:
      init-parameters:
        development: true



spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yx?characterEncoding=utf8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB




  redis:
    host: 192.168.235.151
    port: 7000






mybatis:
  type-aliases-package: com.cn.entity
  mapper-locations: classpath*:com/cn/mapper/*Mapper.xml








logging:
  level:
    root: info
    com.cn.service: debug





